# encoding: UTF-8
require 'set'

# Trigrams are groups of three letters.
# This Class can
#  - build an index mapping trigrams to their strings.
#  - search an index, using a string
#  - convert a string into trigrams
class Trigram
  attr_reader :trigrams

  # generate trigram inverted index
  # arguments:
  # - list: an array of strings
  # returns:
  # a hash, mapping the list to the trigrams extracted from it.
  def self.build_index(list = [])
    this_index = Hash.new()
    list.each_with_index do |item, i|
      item ||= ''
      trigrams = self.to_trigrams(item)
      trigrams.each do |trigram|
        this_index[trigram] ||= []
        this_index[trigram] << i
      end
    end
    this_index
  end

  # Search the index generated by #build_index
  # arguments:
  # - index: a hash, constructed by #build_index
  # - term: a string to search for in the index
  # returns:
  # - matches, as ranked by how many matched trigrams in the string
  def self.search(index, term)
    this_index = index
    search_grams = to_trigrams(term)

    # grab all search index ids where the grams exist
    matched = []
    search_grams.each { |gram| matched << this_index[gram] }
    matched.flatten!
    matched.compact!

    # rank and sort matching ids
    match_counts = Hash.new(0) #zomg, hash can have a default value!
    matched.each{|match| match_counts[match] += 1}

    ranked_results = match_counts.sort { |y, x| x[1]<=>y[1] }
    return ranked_results
  end

  # you could make bigrams by changing 3 => 2 here
  def self.to_trigrams(str)
    self.clean_up(str)

    trigrams = Set.new
    str.split.each do |word|
      (0..word.length - 3).each do |idx|
        trigrams.add(word[idx, 3])
      end
    end

    trigrams
  end

  def self.clean_up(str)
    str.gsub!(/(\s|\(|\)|\-|\.|\/|\'|\,)+/, "")
    str.downcase!
  end

end
